---
name: PHP Linting

on:
  push:
    branches:
      - 'master'
      - 'dev'
      - 'feature/**'

  pull_request:
    types:
      - opened
      - edited

  release:
    types:
      - created
      - edited

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: 'actions/checkout@v2'

        - uses: 'iermentraut/github-action-php-lint@master'


  phpcs:
      runs-on: ubuntu-latest
      steps:
          - uses: 'actions/checkout@v2'
